apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ks
  labels:
    app: hello-ks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-ks
  template:
    metadata:
      labels:
        app: hello-ks
    spec:
      containers:
        - name: hello-ks
          image: hello-ks:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
